// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	ethclient "github.com/ethereum/go-ethereum/ethclient"
	mock "github.com/stretchr/testify/mock"
)

// BondManagerUtils is an autogenerated mock type for the BondManagerUtils type
type BondManagerUtils struct {
	mock.Mock
}

// GetDataBondCollections provides a mock function with given fields: client
func (_m *BondManagerUtils) GetDataBondCollections(client *ethclient.Client) ([]uint16, error) {
	ret := _m.Called(client)

	var r0 []uint16
	if rf, ok := ret.Get(0).(func(*ethclient.Client) []uint16); ok {
		r0 = rf(client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint16)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
