// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	big "math/big"
	RPC "razor/rpc"

	abi "github.com/ethereum/go-ethereum/accounts/abi"

	common "github.com/ethereum/go-ethereum/common"

	context "context"

	ethclient "github.com/ethereum/go-ethereum/ethclient"

	ethereum "github.com/ethereum/go-ethereum"

	mock "github.com/stretchr/testify/mock"

	rpc "github.com/ethereum/go-ethereum/rpc"

	types "github.com/ethereum/go-ethereum/core/types"
)

// ClientUtils is an autogenerated mock type for the ClientUtils type
type ClientUtils struct {
	mock.Mock
}

// BalanceAt provides a mock function with given fields: client, ctx, account, blockNumber
func (_m *ClientUtils) BalanceAt(client *ethclient.Client, ctx context.Context, account common.Address, blockNumber *big.Int) (*big.Int, error) {
	ret := _m.Called(client, ctx, account, blockNumber)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, common.Address, *big.Int) (*big.Int, error)); ok {
		return rf(client, ctx, account, blockNumber)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, common.Address, *big.Int) *big.Int); ok {
		r0 = rf(client, ctx, account, blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, context.Context, common.Address, *big.Int) error); ok {
		r1 = rf(client, ctx, account, blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceAtWithRetry provides a mock function with given fields: rpcParameters, account
func (_m *ClientUtils) BalanceAtWithRetry(rpcParameters RPC.RPCParameters, account common.Address) (*big.Int, error) {
	ret := _m.Called(rpcParameters, account)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, common.Address) (*big.Int, error)); ok {
		return rf(rpcParameters, account)
	}
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, common.Address) *big.Int); ok {
		r0 = rf(rpcParameters, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(RPC.RPCParameters, common.Address) error); ok {
		r1 = rf(rpcParameters, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BatchCall provides a mock function with given fields: rpcParameters, contractABI, contractAddress, methodName, args
func (_m *ClientUtils) BatchCall(rpcParameters RPC.RPCParameters, contractABI *abi.ABI, contractAddress string, methodName string, args [][]interface{}) ([][]interface{}, error) {
	ret := _m.Called(rpcParameters, contractABI, contractAddress, methodName, args)

	var r0 [][]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, *abi.ABI, string, string, [][]interface{}) ([][]interface{}, error)); ok {
		return rf(rpcParameters, contractABI, contractAddress, methodName, args)
	}
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, *abi.ABI, string, string, [][]interface{}) [][]interface{}); ok {
		r0 = rf(rpcParameters, contractABI, contractAddress, methodName, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(RPC.RPCParameters, *abi.ABI, string, string, [][]interface{}) error); ok {
		r1 = rf(rpcParameters, contractABI, contractAddress, methodName, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBatchCalls provides a mock function with given fields: contractABI, contractAddress, methodName, args
func (_m *ClientUtils) CreateBatchCalls(contractABI *abi.ABI, contractAddress string, methodName string, args [][]interface{}) ([]rpc.BatchElem, error) {
	ret := _m.Called(contractABI, contractAddress, methodName, args)

	var r0 []rpc.BatchElem
	var r1 error
	if rf, ok := ret.Get(0).(func(*abi.ABI, string, string, [][]interface{}) ([]rpc.BatchElem, error)); ok {
		return rf(contractABI, contractAddress, methodName, args)
	}
	if rf, ok := ret.Get(0).(func(*abi.ABI, string, string, [][]interface{}) []rpc.BatchElem); ok {
		r0 = rf(contractABI, contractAddress, methodName, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rpc.BatchElem)
		}
	}

	if rf, ok := ret.Get(1).(func(*abi.ABI, string, string, [][]interface{}) error); ok {
		r1 = rf(contractABI, contractAddress, methodName, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstimateGas provides a mock function with given fields: client, ctx, msg
func (_m *ClientUtils) EstimateGas(client *ethclient.Client, ctx context.Context, msg ethereum.CallMsg) (uint64, error) {
	ret := _m.Called(client, ctx, msg)

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, ethereum.CallMsg) (uint64, error)); ok {
		return rf(client, ctx, msg)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, ethereum.CallMsg) uint64); ok {
		r0 = rf(client, ctx, msg)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, context.Context, ethereum.CallMsg) error); ok {
		r1 = rf(client, ctx, msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstimateGasWithRetry provides a mock function with given fields: rpcParameters, message
func (_m *ClientUtils) EstimateGasWithRetry(rpcParameters RPC.RPCParameters, message ethereum.CallMsg) (uint64, error) {
	ret := _m.Called(rpcParameters, message)

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, ethereum.CallMsg) (uint64, error)); ok {
		return rf(rpcParameters, message)
	}
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, ethereum.CallMsg) uint64); ok {
		r0 = rf(rpcParameters, message)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(RPC.RPCParameters, ethereum.CallMsg) error); ok {
		r1 = rf(rpcParameters, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilterLogs provides a mock function with given fields: client, ctx, q
func (_m *ClientUtils) FilterLogs(client *ethclient.Client, ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	ret := _m.Called(client, ctx, q)

	var r0 []types.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, ethereum.FilterQuery) ([]types.Log, error)); ok {
		return rf(client, ctx, q)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, ethereum.FilterQuery) []types.Log); ok {
		r0 = rf(client, ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, context.Context, ethereum.FilterQuery) error); ok {
		r1 = rf(client, ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilterLogsWithRetry provides a mock function with given fields: rpcParameters, query
func (_m *ClientUtils) FilterLogsWithRetry(rpcParameters RPC.RPCParameters, query ethereum.FilterQuery) ([]types.Log, error) {
	ret := _m.Called(rpcParameters, query)

	var r0 []types.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, ethereum.FilterQuery) ([]types.Log, error)); ok {
		return rf(rpcParameters, query)
	}
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, ethereum.FilterQuery) []types.Log); ok {
		r0 = rf(rpcParameters, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(RPC.RPCParameters, ethereum.FilterQuery) error); ok {
		r1 = rf(rpcParameters, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockByNumberWithRetry provides a mock function with given fields: rpcParameters, blockNumber
func (_m *ClientUtils) GetBlockByNumberWithRetry(rpcParameters RPC.RPCParameters, blockNumber *big.Int) (*types.Header, error) {
	ret := _m.Called(rpcParameters, blockNumber)

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, *big.Int) (*types.Header, error)); ok {
		return rf(rpcParameters, blockNumber)
	}
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, *big.Int) *types.Header); ok {
		r0 = rf(rpcParameters, blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(RPC.RPCParameters, *big.Int) error); ok {
		r1 = rf(rpcParameters, blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestBlockWithRetry provides a mock function with given fields: rpcParameters
func (_m *ClientUtils) GetLatestBlockWithRetry(rpcParameters RPC.RPCParameters) (*types.Header, error) {
	ret := _m.Called(rpcParameters)

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters) (*types.Header, error)); ok {
		return rf(rpcParameters)
	}
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters) *types.Header); ok {
		r0 = rf(rpcParameters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(RPC.RPCParameters) error); ok {
		r1 = rf(rpcParameters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNonceAtWithRetry provides a mock function with given fields: rpcParameters, accountAddress
func (_m *ClientUtils) GetNonceAtWithRetry(rpcParameters RPC.RPCParameters, accountAddress common.Address) (uint64, error) {
	ret := _m.Called(rpcParameters, accountAddress)

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, common.Address) (uint64, error)); ok {
		return rf(rpcParameters, accountAddress)
	}
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, common.Address) uint64); ok {
		r0 = rf(rpcParameters, accountAddress)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(RPC.RPCParameters, common.Address) error); ok {
		r1 = rf(rpcParameters, accountAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HeaderByNumber provides a mock function with given fields: client, ctx, number
func (_m *ClientUtils) HeaderByNumber(client *ethclient.Client, ctx context.Context, number *big.Int) (*types.Header, error) {
	ret := _m.Called(client, ctx, number)

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, *big.Int) (*types.Header, error)); ok {
		return rf(client, ctx, number)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, *big.Int) *types.Header); ok {
		r0 = rf(client, ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, context.Context, *big.Int) error); ok {
		r1 = rf(client, ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NonceAt provides a mock function with given fields: client, ctx, account
func (_m *ClientUtils) NonceAt(client *ethclient.Client, ctx context.Context, account common.Address) (uint64, error) {
	ret := _m.Called(client, ctx, account)

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, common.Address) (uint64, error)); ok {
		return rf(client, ctx, account)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, common.Address) uint64); ok {
		r0 = rf(client, ctx, account)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, context.Context, common.Address) error); ok {
		r1 = rf(client, ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PerformBatchCall provides a mock function with given fields: rpcParameters, calls
func (_m *ClientUtils) PerformBatchCall(rpcParameters RPC.RPCParameters, calls []rpc.BatchElem) error {
	ret := _m.Called(rpcParameters, calls)

	var r0 error
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters, []rpc.BatchElem) error); ok {
		r0 = rf(rpcParameters, calls)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SuggestGasPrice provides a mock function with given fields: client, ctx
func (_m *ClientUtils) SuggestGasPrice(client *ethclient.Client, ctx context.Context) (*big.Int, error) {
	ret := _m.Called(client, ctx)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context) (*big.Int, error)); ok {
		return rf(client, ctx)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context) *big.Int); ok {
		r0 = rf(client, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, context.Context) error); ok {
		r1 = rf(client, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SuggestGasPriceWithRetry provides a mock function with given fields: rpcParameters
func (_m *ClientUtils) SuggestGasPriceWithRetry(rpcParameters RPC.RPCParameters) (*big.Int, error) {
	ret := _m.Called(rpcParameters)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters) (*big.Int, error)); ok {
		return rf(rpcParameters)
	}
	if rf, ok := ret.Get(0).(func(RPC.RPCParameters) *big.Int); ok {
		r0 = rf(rpcParameters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(RPC.RPCParameters) error); ok {
		r1 = rf(rpcParameters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionReceipt provides a mock function with given fields: client, ctx, txHash
func (_m *ClientUtils) TransactionReceipt(client *ethclient.Client, ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	ret := _m.Called(client, ctx, txHash)

	var r0 *types.Receipt
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, common.Hash) (*types.Receipt, error)); ok {
		return rf(client, ctx, txHash)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, context.Context, common.Hash) *types.Receipt); ok {
		r0 = rf(client, ctx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Receipt)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, context.Context, common.Hash) error); ok {
		r1 = rf(client, ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientUtils creates a new instance of ClientUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientUtils(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientUtils {
	mock := &ClientUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
