// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	pflag "github.com/spf13/pflag"
	mock "github.com/stretchr/testify/mock"
)

// FlagSetUtils is an autogenerated mock type for the FlagSetUtils type
type FlagSetUtils struct {
	mock.Mock
}

// GetLogFileName provides a mock function with given fields: flagSet
func (_m *FlagSetUtils) GetLogFileName(flagSet *pflag.FlagSet) (string, error) {
	ret := _m.Called(flagSet)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*pflag.FlagSet) (string, error)); ok {
		return rf(flagSet)
	}
	if rf, ok := ret.Get(0).(func(*pflag.FlagSet) string); ok {
		r0 = rf(flagSet)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*pflag.FlagSet) error); ok {
		r1 = rf(flagSet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFlagSetUtils creates a new instance of FlagSetUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlagSetUtils(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlagSetUtils {
	mock := &FlagSetUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
