// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// IOUtils is an autogenerated mock type for the IOUtils type
type IOUtils struct {
	mock.Mock
}

// ReadAll provides a mock function with given fields: body
func (_m *IOUtils) ReadAll(body io.ReadCloser) ([]byte, error) {
	ret := _m.Called(body)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(io.ReadCloser) ([]byte, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(io.ReadCloser) []byte); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(io.ReadCloser) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOUtils creates a new instance of IOUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOUtils(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOUtils {
	mock := &IOUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
