// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	io "io"
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// IoutilUtils is an autogenerated mock type for the IoutilUtils type
type IoutilUtils struct {
	mock.Mock
}

// ReadAll provides a mock function with given fields: body
func (_m *IoutilUtils) ReadAll(body io.ReadCloser) ([]byte, error) {
	ret := _m.Called(body)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(io.ReadCloser) []byte); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.ReadCloser) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadFile provides a mock function with given fields: filename
func (_m *IoutilUtils) ReadFile(filename string) ([]byte, error) {
	ret := _m.Called(filename)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteFile provides a mock function with given fields: filename, data, perm
func (_m *IoutilUtils) WriteFile(filename string, data []byte, perm fs.FileMode) error {
	ret := _m.Called(filename, data, perm)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = rf(filename, data, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
