// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	retry "github.com/avast/retry-go"
	mock "github.com/stretchr/testify/mock"
)

// RetryUtils is an autogenerated mock type for the RetryUtils type
type RetryUtils struct {
	mock.Mock
}

// RetryAttempts provides a mock function with given fields: _a0
func (_m *RetryUtils) RetryAttempts(_a0 uint) retry.Option {
	ret := _m.Called(_a0)

	var r0 retry.Option
	if rf, ok := ret.Get(0).(func(uint) retry.Option); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(retry.Option)
		}
	}

	return r0
}
