// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	big "math/big"
	bindings "razor/pkg/bindings"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"
)

// StakedTokenUtils is an autogenerated mock type for the StakedTokenUtils type
type StakedTokenUtils struct {
	mock.Mock
}

// BalanceOf provides a mock function with given fields: stakedToken, callOpts, address
func (_m *StakedTokenUtils) BalanceOf(stakedToken *bindings.StakedToken, callOpts *bind.CallOpts, address common.Address) (*big.Int, error) {
	ret := _m.Called(stakedToken, callOpts, address)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(*bindings.StakedToken, *bind.CallOpts, common.Address) *big.Int); ok {
		r0 = rf(stakedToken, callOpts, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*bindings.StakedToken, *bind.CallOpts, common.Address) error); ok {
		r1 = rf(stakedToken, callOpts, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStakedTokenUtils interface {
	mock.TestingT
	Cleanup(func())
}

// NewStakedTokenUtils creates a new instance of StakedTokenUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStakedTokenUtils(t mockConstructorTestingTNewStakedTokenUtils) *StakedTokenUtils {
	mock := &StakedTokenUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
