// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TimeUtils is an autogenerated mock type for the TimeUtils type
type TimeUtils struct {
	mock.Mock
}

// Sleep provides a mock function with given fields: duration
func (_m *TimeUtils) Sleep(duration time.Duration) {
	_m.Called(duration)
}

// NewTimeUtils creates a new instance of TimeUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeUtils(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeUtils {
	mock := &TimeUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
