// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TimeUtils is an autogenerated mock type for the TimeUtils type
type TimeUtils struct {
	mock.Mock
}

// Sleep provides a mock function with given fields: duration
func (_m *TimeUtils) Sleep(duration time.Duration) {
	_m.Called(duration)
}
