// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	big "math/big"
	bindings "razor/pkg/bindings"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"

	cache "razor/cache"

	client "razor/client"

	common "github.com/ethereum/go-ethereum/common"

	ethclient "github.com/ethereum/go-ethereum/ethclient"

	mock "github.com/stretchr/testify/mock"

	pflag "github.com/spf13/pflag"

	types "razor/core/types"
)

// Utils is an autogenerated mock type for the Utils type
type Utils struct {
	mock.Mock
}

// AddJobToJSON provides a mock function with given fields: fileName, job
func (_m *Utils) AddJobToJSON(fileName string, job *types.StructsJob) error {
	ret := _m.Called(fileName, job)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *types.StructsJob) error); ok {
		r0 = rf(fileName, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Aggregate provides a mock function with given fields: _a0, previousEpoch, collection, localCache, httpClient
func (_m *Utils) Aggregate(_a0 *ethclient.Client, previousEpoch uint32, collection bindings.StructsCollection, localCache *cache.LocalCache, httpClient *client.HttpClient) (*big.Int, error) {
	ret := _m.Called(_a0, previousEpoch, collection, localCache, httpClient)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, bindings.StructsCollection, *cache.LocalCache, *client.HttpClient) (*big.Int, error)); ok {
		return rf(_a0, previousEpoch, collection, localCache, httpClient)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, bindings.StructsCollection, *cache.LocalCache, *client.HttpClient) *big.Int); ok {
		r0 = rf(_a0, previousEpoch, collection, localCache, httpClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32, bindings.StructsCollection, *cache.LocalCache, *client.HttpClient) error); ok {
		r1 = rf(_a0, previousEpoch, collection, localCache, httpClient)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AssignPassword provides a mock function with given fields: flagSet
func (_m *Utils) AssignPassword(flagSet *pflag.FlagSet) string {
	ret := _m.Called(flagSet)

	var r0 string
	if rf, ok := ret.Get(0).(func(*pflag.FlagSet) string); ok {
		r0 = rf(flagSet)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AssignStakerId provides a mock function with given fields: flagSet, _a1, address
func (_m *Utils) AssignStakerId(flagSet *pflag.FlagSet, _a1 *ethclient.Client, address string) (uint32, error) {
	ret := _m.Called(flagSet, _a1, address)

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*pflag.FlagSet, *ethclient.Client, string) (uint32, error)); ok {
		return rf(flagSet, _a1, address)
	}
	if rf, ok := ret.Get(0).(func(*pflag.FlagSet, *ethclient.Client, string) uint32); ok {
		r0 = rf(flagSet, _a1, address)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(*pflag.FlagSet, *ethclient.Client, string) error); ok {
		r1 = rf(flagSet, _a1, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculateBlockTime provides a mock function with given fields: _a0
func (_m *Utils) CalculateBlockTime(_a0 *ethclient.Client) int64 {
	ret := _m.Called(_a0)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*ethclient.Client) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// CalculateSalt provides a mock function with given fields: epoch, medians
func (_m *Utils) CalculateSalt(epoch uint32, medians []*big.Int) [32]byte {
	ret := _m.Called(epoch, medians)

	var r0 [32]byte
	if rf, ok := ret.Get(0).(func(uint32, []*big.Int) [32]byte); ok {
		r0 = rf(epoch, medians)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([32]byte)
		}
	}

	return r0
}

// CheckAmountAndBalance provides a mock function with given fields: amountInWei, balance
func (_m *Utils) CheckAmountAndBalance(amountInWei *big.Int, balance *big.Int) *big.Int {
	ret := _m.Called(amountInWei, balance)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(*big.Int, *big.Int) *big.Int); ok {
		r0 = rf(amountInWei, balance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// CheckEthBalanceIsZero provides a mock function with given fields: _a0, address
func (_m *Utils) CheckEthBalanceIsZero(_a0 *ethclient.Client, address string) {
	_m.Called(_a0, address)
}

// CheckPassword provides a mock function with given fields: address, password
func (_m *Utils) CheckPassword(address string, password string) error {
	ret := _m.Called(address, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(address, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckTransactionReceipt provides a mock function with given fields: _a0, _txHash
func (_m *Utils) CheckTransactionReceipt(_a0 *ethclient.Client, _txHash string) int {
	ret := _m.Called(_a0, _txHash)

	var r0 int
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string) int); ok {
		r0 = rf(_a0, _txHash)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ConnectToClient provides a mock function with given fields: provider
func (_m *Utils) ConnectToClient(provider string) *ethclient.Client {
	ret := _m.Called(provider)

	var r0 *ethclient.Client
	if rf, ok := ret.Get(0).(func(string) *ethclient.Client); ok {
		r0 = rf(provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethclient.Client)
		}
	}

	return r0
}

// DeleteJobFromJSON provides a mock function with given fields: fileName, jobId
func (_m *Utils) DeleteJobFromJSON(fileName string, jobId string) error {
	ret := _m.Called(fileName, jobId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(fileName, jobId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EstimateBlockNumberAtEpochBeginning provides a mock function with given fields: _a0, currentBlockNumber
func (_m *Utils) EstimateBlockNumberAtEpochBeginning(_a0 *ethclient.Client, currentBlockNumber *big.Int) (*big.Int, error) {
	ret := _m.Called(_a0, currentBlockNumber)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, *big.Int) (*big.Int, error)); ok {
		return rf(_a0, currentBlockNumber)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, *big.Int) *big.Int); ok {
		r0 = rf(_a0, currentBlockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, *big.Int) error); ok {
		r1 = rf(_a0, currentBlockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchBalance provides a mock function with given fields: _a0, accountAddress
func (_m *Utils) FetchBalance(_a0 *ethclient.Client, accountAddress string) (*big.Int, error) {
	ret := _m.Called(_a0, accountAddress)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string) (*big.Int, error)); ok {
		return rf(_a0, accountAddress)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string) *big.Int); ok {
		r0 = rf(_a0, accountAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, string) error); ok {
		r1 = rf(_a0, accountAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchPreviousValue provides a mock function with given fields: _a0, epoch, assetId
func (_m *Utils) FetchPreviousValue(_a0 *ethclient.Client, epoch uint32, assetId uint16) (*big.Int, error) {
	ret := _m.Called(_a0, epoch, assetId)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint16) (*big.Int, error)); ok {
		return rf(_a0, epoch, assetId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint16) *big.Int); ok {
		r0 = rf(_a0, epoch, assetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32, uint16) error); ok {
		r1 = rf(_a0, epoch, assetId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveCollection provides a mock function with given fields: _a0, collectionId
func (_m *Utils) GetActiveCollection(_a0 *ethclient.Client, collectionId uint16) (bindings.StructsCollection, error) {
	ret := _m.Called(_a0, collectionId)

	var r0 bindings.StructsCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) (bindings.StructsCollection, error)); ok {
		return rf(_a0, collectionId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) bindings.StructsCollection); ok {
		r0 = rf(_a0, collectionId)
	} else {
		r0 = ret.Get(0).(bindings.StructsCollection)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint16) error); ok {
		r1 = rf(_a0, collectionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveCollectionIds provides a mock function with given fields: _a0
func (_m *Utils) GetActiveCollectionIds(_a0 *ethclient.Client) ([]uint16, error) {
	ret := _m.Called(_a0)

	var r0 []uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) ([]uint16, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) []uint16); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint16)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveJob provides a mock function with given fields: _a0, jobId
func (_m *Utils) GetActiveJob(_a0 *ethclient.Client, jobId uint16) (bindings.StructsJob, error) {
	ret := _m.Called(_a0, jobId)

	var r0 bindings.StructsJob
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) (bindings.StructsJob, error)); ok {
		return rf(_a0, jobId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) bindings.StructsJob); ok {
		r0 = rf(_a0, jobId)
	} else {
		r0 = ret.Get(0).(bindings.StructsJob)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint16) error); ok {
		r1 = rf(_a0, jobId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAggregatedDataOfCollection provides a mock function with given fields: _a0, collectionId, epoch, localCache, httpClient
func (_m *Utils) GetAggregatedDataOfCollection(_a0 *ethclient.Client, collectionId uint16, epoch uint32, localCache *cache.LocalCache, httpClient *client.HttpClient) (*big.Int, error) {
	ret := _m.Called(_a0, collectionId, epoch, localCache, httpClient)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16, uint32, *cache.LocalCache, *client.HttpClient) (*big.Int, error)); ok {
		return rf(_a0, collectionId, epoch, localCache, httpClient)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16, uint32, *cache.LocalCache, *client.HttpClient) *big.Int); ok {
		r0 = rf(_a0, collectionId, epoch, localCache, httpClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint16, uint32, *cache.LocalCache, *client.HttpClient) error); ok {
		r1 = rf(_a0, collectionId, epoch, localCache, httpClient)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCollections provides a mock function with given fields: _a0
func (_m *Utils) GetAllCollections(_a0 *ethclient.Client) ([]bindings.StructsCollection, error) {
	ret := _m.Called(_a0)

	var r0 []bindings.StructsCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) ([]bindings.StructsCollection, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) []bindings.StructsCollection); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bindings.StructsCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAssignedCollections provides a mock function with given fields: _a0, numActiveCollections, seed
func (_m *Utils) GetAssignedCollections(_a0 *ethclient.Client, numActiveCollections uint16, seed []byte) (map[int]bool, []*big.Int, error) {
	ret := _m.Called(_a0, numActiveCollections, seed)

	var r0 map[int]bool
	var r1 []*big.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16, []byte) (map[int]bool, []*big.Int, error)); ok {
		return rf(_a0, numActiveCollections, seed)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16, []byte) map[int]bool); ok {
		r0 = rf(_a0, numActiveCollections, seed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint16, []byte) []*big.Int); ok {
		r1 = rf(_a0, numActiveCollections, seed)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*big.Int)
		}
	}

	if rf, ok := ret.Get(2).(func(*ethclient.Client, uint16, []byte) error); ok {
		r2 = rf(_a0, numActiveCollections, seed)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetBlock provides a mock function with given fields: _a0, epoch
func (_m *Utils) GetBlock(_a0 *ethclient.Client, epoch uint32) (bindings.StructsBlock, error) {
	ret := _m.Called(_a0, epoch)

	var r0 bindings.StructsBlock
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) (bindings.StructsBlock, error)); ok {
		return rf(_a0, epoch)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) bindings.StructsBlock); ok {
		r0 = rf(_a0, epoch)
	} else {
		r0 = ret.Get(0).(bindings.StructsBlock)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32) error); ok {
		r1 = rf(_a0, epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockIndexToBeConfirmed provides a mock function with given fields: _a0
func (_m *Utils) GetBlockIndexToBeConfirmed(_a0 *ethclient.Client) (int8, error) {
	ret := _m.Called(_a0)

	var r0 int8
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (int8, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) int8); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int8)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockManager provides a mock function with given fields: _a0
func (_m *Utils) GetBlockManager(_a0 *ethclient.Client) *bindings.BlockManager {
	ret := _m.Called(_a0)

	var r0 *bindings.BlockManager
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *bindings.BlockManager); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.BlockManager)
		}
	}

	return r0
}

// GetBlockManagerWithOpts provides a mock function with given fields: _a0
func (_m *Utils) GetBlockManagerWithOpts(_a0 *ethclient.Client) (*bindings.BlockManager, bind.CallOpts) {
	ret := _m.Called(_a0)

	var r0 *bindings.BlockManager
	var r1 bind.CallOpts
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (*bindings.BlockManager, bind.CallOpts)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *bindings.BlockManager); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.BlockManager)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) bind.CallOpts); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bind.CallOpts)
	}

	return r0, r1
}

// GetBufferedState provides a mock function with given fields: _a0, buffer
func (_m *Utils) GetBufferedState(_a0 *ethclient.Client, buffer int32) (int64, error) {
	ret := _m.Called(_a0, buffer)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, int32) (int64, error)); ok {
		return rf(_a0, buffer)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, int32) int64); ok {
		r0 = rf(_a0, buffer)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, int32) error); ok {
		r1 = rf(_a0, buffer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCollection provides a mock function with given fields: _a0, collectionId
func (_m *Utils) GetCollection(_a0 *ethclient.Client, collectionId uint16) (bindings.StructsCollection, error) {
	ret := _m.Called(_a0, collectionId)

	var r0 bindings.StructsCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) (bindings.StructsCollection, error)); ok {
		return rf(_a0, collectionId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) bindings.StructsCollection); ok {
		r0 = rf(_a0, collectionId)
	} else {
		r0 = ret.Get(0).(bindings.StructsCollection)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint16) error); ok {
		r1 = rf(_a0, collectionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCollectionIdFromIndex provides a mock function with given fields: _a0, medianIndex
func (_m *Utils) GetCollectionIdFromIndex(_a0 *ethclient.Client, medianIndex uint16) (uint16, error) {
	ret := _m.Called(_a0, medianIndex)

	var r0 uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) (uint16, error)); ok {
		return rf(_a0, medianIndex)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) uint16); ok {
		r0 = rf(_a0, medianIndex)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint16) error); ok {
		r1 = rf(_a0, medianIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCollectionIdFromLeafId provides a mock function with given fields: _a0, leafId
func (_m *Utils) GetCollectionIdFromLeafId(_a0 *ethclient.Client, leafId uint16) (uint16, error) {
	ret := _m.Called(_a0, leafId)

	var r0 uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) (uint16, error)); ok {
		return rf(_a0, leafId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) uint16); ok {
		r0 = rf(_a0, leafId)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint16) error); ok {
		r1 = rf(_a0, leafId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCollectionManager provides a mock function with given fields: _a0
func (_m *Utils) GetCollectionManager(_a0 *ethclient.Client) *bindings.CollectionManager {
	ret := _m.Called(_a0)

	var r0 *bindings.CollectionManager
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *bindings.CollectionManager); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.CollectionManager)
		}
	}

	return r0
}

// GetCollectionManagerWithOpts provides a mock function with given fields: _a0
func (_m *Utils) GetCollectionManagerWithOpts(_a0 *ethclient.Client) (*bindings.CollectionManager, bind.CallOpts) {
	ret := _m.Called(_a0)

	var r0 *bindings.CollectionManager
	var r1 bind.CallOpts
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (*bindings.CollectionManager, bind.CallOpts)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *bindings.CollectionManager); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.CollectionManager)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) bind.CallOpts); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bind.CallOpts)
	}

	return r0, r1
}

// GetCommitment provides a mock function with given fields: _a0, address
func (_m *Utils) GetCommitment(_a0 *ethclient.Client, address string) (types.Commitment, error) {
	ret := _m.Called(_a0, address)

	var r0 types.Commitment
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string) (types.Commitment, error)); ok {
		return rf(_a0, address)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string) types.Commitment); ok {
		r0 = rf(_a0, address)
	} else {
		r0 = ret.Get(0).(types.Commitment)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, string) error); ok {
		r1 = rf(_a0, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataToCommitFromJob provides a mock function with given fields: job, localCache, httpClient
func (_m *Utils) GetDataToCommitFromJob(job bindings.StructsJob, localCache *cache.LocalCache, httpClient *client.HttpClient) (*big.Int, error) {
	ret := _m.Called(job, localCache, httpClient)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(bindings.StructsJob, *cache.LocalCache, *client.HttpClient) (*big.Int, error)); ok {
		return rf(job, localCache, httpClient)
	}
	if rf, ok := ret.Get(0).(func(bindings.StructsJob, *cache.LocalCache, *client.HttpClient) *big.Int); ok {
		r0 = rf(job, localCache, httpClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(bindings.StructsJob, *cache.LocalCache, *client.HttpClient) error); ok {
		r1 = rf(job, localCache, httpClient)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataToCommitFromJobs provides a mock function with given fields: jobs, localCache, httpClient
func (_m *Utils) GetDataToCommitFromJobs(jobs []bindings.StructsJob, localCache *cache.LocalCache, httpClient *client.HttpClient) ([]*big.Int, []uint8) {
	ret := _m.Called(jobs, localCache, httpClient)

	var r0 []*big.Int
	var r1 []uint8
	if rf, ok := ret.Get(0).(func([]bindings.StructsJob, *cache.LocalCache, *client.HttpClient) ([]*big.Int, []uint8)); ok {
		return rf(jobs, localCache, httpClient)
	}
	if rf, ok := ret.Get(0).(func([]bindings.StructsJob, *cache.LocalCache, *client.HttpClient) []*big.Int); ok {
		r0 = rf(jobs, localCache, httpClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func([]bindings.StructsJob, *cache.LocalCache, *client.HttpClient) []uint8); ok {
		r1 = rf(jobs, localCache, httpClient)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]uint8)
		}
	}

	return r0, r1
}

// GetEpoch provides a mock function with given fields: _a0
func (_m *Utils) GetEpoch(_a0 *ethclient.Client) (uint32, error) {
	ret := _m.Called(_a0)

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint32, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint32); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEpochLastCommitted provides a mock function with given fields: _a0, stakerId
func (_m *Utils) GetEpochLastCommitted(_a0 *ethclient.Client, stakerId uint32) (uint32, error) {
	ret := _m.Called(_a0, stakerId)

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) (uint32, error)); ok {
		return rf(_a0, stakerId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) uint32); ok {
		r0 = rf(_a0, stakerId)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32) error); ok {
		r1 = rf(_a0, stakerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEpochLastProposed provides a mock function with given fields: _a0, stakerId
func (_m *Utils) GetEpochLastProposed(_a0 *ethclient.Client, stakerId uint32) (uint32, error) {
	ret := _m.Called(_a0, stakerId)

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) (uint32, error)); ok {
		return rf(_a0, stakerId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) uint32); ok {
		r0 = rf(_a0, stakerId)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32) error); ok {
		r1 = rf(_a0, stakerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEpochLastRevealed provides a mock function with given fields: _a0, stakerId
func (_m *Utils) GetEpochLastRevealed(_a0 *ethclient.Client, stakerId uint32) (uint32, error) {
	ret := _m.Called(_a0, stakerId)

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) (uint32, error)); ok {
		return rf(_a0, stakerId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) uint32); ok {
		r0 = rf(_a0, stakerId)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32) error); ok {
		r1 = rf(_a0, stakerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEpochLimitForUpdateCommission provides a mock function with given fields: _a0
func (_m *Utils) GetEpochLimitForUpdateCommission(_a0 *ethclient.Client) (uint16, error) {
	ret := _m.Called(_a0)

	var r0 uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint16, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint16); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInfluenceSnapshot provides a mock function with given fields: _a0, stakerId, epoch
func (_m *Utils) GetInfluenceSnapshot(_a0 *ethclient.Client, stakerId uint32, epoch uint32) (*big.Int, error) {
	ret := _m.Called(_a0, stakerId, epoch)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint32) (*big.Int, error)); ok {
		return rf(_a0, stakerId, epoch)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint32) *big.Int); ok {
		r0 = rf(_a0, stakerId, epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32, uint32) error); ok {
		r1 = rf(_a0, stakerId, epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobs provides a mock function with given fields: _a0
func (_m *Utils) GetJobs(_a0 *ethclient.Client) ([]bindings.StructsJob, error) {
	ret := _m.Called(_a0)

	var r0 []bindings.StructsJob
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) ([]bindings.StructsJob, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) []bindings.StructsJob); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bindings.StructsJob)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeafIdOfACollection provides a mock function with given fields: _a0, collectionId
func (_m *Utils) GetLeafIdOfACollection(_a0 *ethclient.Client, collectionId uint16) (uint16, error) {
	ret := _m.Called(_a0, collectionId)

	var r0 uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) (uint16, error)); ok {
		return rf(_a0, collectionId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint16) uint16); ok {
		r0 = rf(_a0, collectionId)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint16) error); ok {
		r1 = rf(_a0, collectionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLock provides a mock function with given fields: _a0, address, stakerId, lockType
func (_m *Utils) GetLock(_a0 *ethclient.Client, address string, stakerId uint32, lockType uint8) (types.Locks, error) {
	ret := _m.Called(_a0, address, stakerId, lockType)

	var r0 types.Locks
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string, uint32, uint8) (types.Locks, error)); ok {
		return rf(_a0, address, stakerId, lockType)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string, uint32, uint8) types.Locks); ok {
		r0 = rf(_a0, address, stakerId, lockType)
	} else {
		r0 = ret.Get(0).(types.Locks)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, string, uint32, uint8) error); ok {
		r1 = rf(_a0, address, stakerId, lockType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMaxAltBlocks provides a mock function with given fields: _a0
func (_m *Utils) GetMaxAltBlocks(_a0 *ethclient.Client) (uint8, error) {
	ret := _m.Called(_a0)

	var r0 uint8
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint8, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint8); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint8)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMaxCommission provides a mock function with given fields: _a0
func (_m *Utils) GetMaxCommission(_a0 *ethclient.Client) (uint8, error) {
	ret := _m.Called(_a0)

	var r0 uint8
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint8, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint8); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint8)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMinSafeRazor provides a mock function with given fields: _a0
func (_m *Utils) GetMinSafeRazor(_a0 *ethclient.Client) (*big.Int, error) {
	ret := _m.Called(_a0)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (*big.Int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *big.Int); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMinStakeAmount provides a mock function with given fields: _a0
func (_m *Utils) GetMinStakeAmount(_a0 *ethclient.Client) (*big.Int, error) {
	ret := _m.Called(_a0)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (*big.Int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *big.Int); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNumActiveCollections provides a mock function with given fields: _a0
func (_m *Utils) GetNumActiveCollections(_a0 *ethclient.Client) (uint16, error) {
	ret := _m.Called(_a0)

	var r0 uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint16, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint16); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNumCollections provides a mock function with given fields: _a0
func (_m *Utils) GetNumCollections(_a0 *ethclient.Client) (uint16, error) {
	ret := _m.Called(_a0)

	var r0 uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint16, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint16); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNumberOfProposedBlocks provides a mock function with given fields: _a0, epoch
func (_m *Utils) GetNumberOfProposedBlocks(_a0 *ethclient.Client, epoch uint32) (uint8, error) {
	ret := _m.Called(_a0, epoch)

	var r0 uint8
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) (uint8, error)); ok {
		return rf(_a0, epoch)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) uint8); ok {
		r0 = rf(_a0, epoch)
	} else {
		r0 = ret.Get(0).(uint8)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32) error); ok {
		r1 = rf(_a0, epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNumberOfStakers provides a mock function with given fields: _a0
func (_m *Utils) GetNumberOfStakers(_a0 *ethclient.Client) (uint32, error) {
	ret := _m.Called(_a0)

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint32, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint32); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOptions provides a mock function with given fields:
func (_m *Utils) GetOptions() bind.CallOpts {
	ret := _m.Called()

	var r0 bind.CallOpts
	if rf, ok := ret.Get(0).(func() bind.CallOpts); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bind.CallOpts)
	}

	return r0
}

// GetProposedBlock provides a mock function with given fields: _a0, epoch, proposedBlockId
func (_m *Utils) GetProposedBlock(_a0 *ethclient.Client, epoch uint32, proposedBlockId uint32) (bindings.StructsBlock, error) {
	ret := _m.Called(_a0, epoch, proposedBlockId)

	var r0 bindings.StructsBlock
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint32) (bindings.StructsBlock, error)); ok {
		return rf(_a0, epoch, proposedBlockId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint32) bindings.StructsBlock); ok {
		r0 = rf(_a0, epoch, proposedBlockId)
	} else {
		r0 = ret.Get(0).(bindings.StructsBlock)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32, uint32) error); ok {
		r1 = rf(_a0, epoch, proposedBlockId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRemainingTimeOfCurrentState provides a mock function with given fields: _a0, bufferPercent
func (_m *Utils) GetRemainingTimeOfCurrentState(_a0 *ethclient.Client, bufferPercent int32) (int64, error) {
	ret := _m.Called(_a0, bufferPercent)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, int32) (int64, error)); ok {
		return rf(_a0, bufferPercent)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, int32) int64); ok {
		r0 = rf(_a0, bufferPercent)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, int32) error); ok {
		r1 = rf(_a0, bufferPercent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRogueRandomValue provides a mock function with given fields: value
func (_m *Utils) GetRogueRandomValue(value int) *big.Int {
	ret := _m.Called(value)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(int) *big.Int); ok {
		r0 = rf(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// GetSortedProposedBlockId provides a mock function with given fields: _a0, epoch, index
func (_m *Utils) GetSortedProposedBlockId(_a0 *ethclient.Client, epoch uint32, index *big.Int) (uint32, error) {
	ret := _m.Called(_a0, epoch, index)

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, *big.Int) (uint32, error)); ok {
		return rf(_a0, epoch, index)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, *big.Int) uint32); ok {
		r0 = rf(_a0, epoch, index)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32, *big.Int) error); ok {
		r1 = rf(_a0, epoch, index)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSortedProposedBlockIds provides a mock function with given fields: _a0, epoch
func (_m *Utils) GetSortedProposedBlockIds(_a0 *ethclient.Client, epoch uint32) ([]uint32, error) {
	ret := _m.Called(_a0, epoch)

	var r0 []uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) ([]uint32, error)); ok {
		return rf(_a0, epoch)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) []uint32); ok {
		r0 = rf(_a0, epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint32)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32) error); ok {
		r1 = rf(_a0, epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStake provides a mock function with given fields: _a0, stakerId
func (_m *Utils) GetStake(_a0 *ethclient.Client, stakerId uint32) (*big.Int, error) {
	ret := _m.Called(_a0, stakerId)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) (*big.Int, error)); ok {
		return rf(_a0, stakerId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) *big.Int); ok {
		r0 = rf(_a0, stakerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32) error); ok {
		r1 = rf(_a0, stakerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStakeManager provides a mock function with given fields: _a0
func (_m *Utils) GetStakeManager(_a0 *ethclient.Client) *bindings.StakeManager {
	ret := _m.Called(_a0)

	var r0 *bindings.StakeManager
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *bindings.StakeManager); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.StakeManager)
		}
	}

	return r0
}

// GetStakeManagerWithOpts provides a mock function with given fields: _a0
func (_m *Utils) GetStakeManagerWithOpts(_a0 *ethclient.Client) (*bindings.StakeManager, bind.CallOpts) {
	ret := _m.Called(_a0)

	var r0 *bindings.StakeManager
	var r1 bind.CallOpts
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (*bindings.StakeManager, bind.CallOpts)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *bindings.StakeManager); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.StakeManager)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) bind.CallOpts); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bind.CallOpts)
	}

	return r0, r1
}

// GetStakeSnapshot provides a mock function with given fields: _a0, stakerId, epoch
func (_m *Utils) GetStakeSnapshot(_a0 *ethclient.Client, stakerId uint32, epoch uint32) (*big.Int, error) {
	ret := _m.Called(_a0, stakerId, epoch)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint32) (*big.Int, error)); ok {
		return rf(_a0, stakerId, epoch)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint32) *big.Int); ok {
		r0 = rf(_a0, stakerId, epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32, uint32) error); ok {
		r1 = rf(_a0, stakerId, epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStakedToken provides a mock function with given fields: _a0, tokenAddress
func (_m *Utils) GetStakedToken(_a0 *ethclient.Client, tokenAddress common.Address) *bindings.StakedToken {
	ret := _m.Called(_a0, tokenAddress)

	var r0 *bindings.StakedToken
	if rf, ok := ret.Get(0).(func(*ethclient.Client, common.Address) *bindings.StakedToken); ok {
		r0 = rf(_a0, tokenAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.StakedToken)
		}
	}

	return r0
}

// GetStakedTokenManagerWithOpts provides a mock function with given fields: _a0, tokenAddress
func (_m *Utils) GetStakedTokenManagerWithOpts(_a0 *ethclient.Client, tokenAddress common.Address) (*bindings.StakedToken, bind.CallOpts) {
	ret := _m.Called(_a0, tokenAddress)

	var r0 *bindings.StakedToken
	var r1 bind.CallOpts
	if rf, ok := ret.Get(0).(func(*ethclient.Client, common.Address) (*bindings.StakedToken, bind.CallOpts)); ok {
		return rf(_a0, tokenAddress)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, common.Address) *bindings.StakedToken); ok {
		r0 = rf(_a0, tokenAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.StakedToken)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, common.Address) bind.CallOpts); ok {
		r1 = rf(_a0, tokenAddress)
	} else {
		r1 = ret.Get(1).(bind.CallOpts)
	}

	return r0, r1
}

// GetStaker provides a mock function with given fields: _a0, stakerId
func (_m *Utils) GetStaker(_a0 *ethclient.Client, stakerId uint32) (bindings.StructsStaker, error) {
	ret := _m.Called(_a0, stakerId)

	var r0 bindings.StructsStaker
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) (bindings.StructsStaker, error)); ok {
		return rf(_a0, stakerId)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32) bindings.StructsStaker); ok {
		r0 = rf(_a0, stakerId)
	} else {
		r0 = ret.Get(0).(bindings.StructsStaker)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32) error); ok {
		r1 = rf(_a0, stakerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStakerId provides a mock function with given fields: _a0, address
func (_m *Utils) GetStakerId(_a0 *ethclient.Client, address string) (uint32, error) {
	ret := _m.Called(_a0, address)

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string) (uint32, error)); ok {
		return rf(_a0, address)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string) uint32); ok {
		r0 = rf(_a0, address)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, string) error); ok {
		r1 = rf(_a0, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStakerSRZRBalance provides a mock function with given fields: _a0, staker
func (_m *Utils) GetStakerSRZRBalance(_a0 *ethclient.Client, staker bindings.StructsStaker) (*big.Int, error) {
	ret := _m.Called(_a0, staker)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, bindings.StructsStaker) (*big.Int, error)); ok {
		return rf(_a0, staker)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, bindings.StructsStaker) *big.Int); ok {
		r0 = rf(_a0, staker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, bindings.StructsStaker) error); ok {
		r1 = rf(_a0, staker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStateBuffer provides a mock function with given fields: _a0
func (_m *Utils) GetStateBuffer(_a0 *ethclient.Client) (uint64, error) {
	ret := _m.Called(_a0)

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint64, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenManager provides a mock function with given fields: _a0
func (_m *Utils) GetTokenManager(_a0 *ethclient.Client) *bindings.RAZOR {
	ret := _m.Called(_a0)

	var r0 *bindings.RAZOR
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *bindings.RAZOR); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.RAZOR)
		}
	}

	return r0
}

// GetTotalInfluenceRevealed provides a mock function with given fields: _a0, epoch, medianIndex
func (_m *Utils) GetTotalInfluenceRevealed(_a0 *ethclient.Client, epoch uint32, medianIndex uint16) (*big.Int, error) {
	ret := _m.Called(_a0, epoch, medianIndex)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint16) (*big.Int, error)); ok {
		return rf(_a0, epoch, medianIndex)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint16) *big.Int); ok {
		r0 = rf(_a0, epoch, medianIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32, uint16) error); ok {
		r1 = rf(_a0, epoch, medianIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTxnOpts provides a mock function with given fields: transactionData
func (_m *Utils) GetTxnOpts(transactionData types.TransactionOptions) *bind.TransactOpts {
	ret := _m.Called(transactionData)

	var r0 *bind.TransactOpts
	if rf, ok := ret.Get(0).(func(types.TransactionOptions) *bind.TransactOpts); ok {
		r0 = rf(transactionData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bind.TransactOpts)
		}
	}

	return r0
}

// GetUint32 provides a mock function with given fields: flagSet, name
func (_m *Utils) GetUint32(flagSet *pflag.FlagSet, name string) (uint32, error) {
	ret := _m.Called(flagSet, name)

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*pflag.FlagSet, string) (uint32, error)); ok {
		return rf(flagSet, name)
	}
	if rf, ok := ret.Get(0).(func(*pflag.FlagSet, string) uint32); ok {
		r0 = rf(flagSet, name)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(*pflag.FlagSet, string) error); ok {
		r1 = rf(flagSet, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoteManager provides a mock function with given fields: _a0
func (_m *Utils) GetVoteManager(_a0 *ethclient.Client) *bindings.VoteManager {
	ret := _m.Called(_a0)

	var r0 *bindings.VoteManager
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *bindings.VoteManager); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.VoteManager)
		}
	}

	return r0
}

// GetVoteManagerWithOpts provides a mock function with given fields: _a0
func (_m *Utils) GetVoteManagerWithOpts(_a0 *ethclient.Client) (*bindings.VoteManager, bind.CallOpts) {
	ret := _m.Called(_a0)

	var r0 *bindings.VoteManager
	var r1 bind.CallOpts
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (*bindings.VoteManager, bind.CallOpts)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) *bindings.VoteManager); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bindings.VoteManager)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) bind.CallOpts); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bind.CallOpts)
	}

	return r0, r1
}

// GetVoteValue provides a mock function with given fields: _a0, epoch, stakerId, medianIndex
func (_m *Utils) GetVoteValue(_a0 *ethclient.Client, epoch uint32, stakerId uint32, medianIndex uint16) (*big.Int, error) {
	ret := _m.Called(_a0, epoch, stakerId, medianIndex)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint32, uint16) (*big.Int, error)); ok {
		return rf(_a0, epoch, stakerId, medianIndex)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, uint32, uint32, uint16) *big.Int); ok {
		r0 = rf(_a0, epoch, stakerId, medianIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, uint32, uint32, uint16) error); ok {
		r1 = rf(_a0, epoch, stakerId, medianIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawInitiationPeriod provides a mock function with given fields: _a0
func (_m *Utils) GetWithdrawInitiationPeriod(_a0 *ethclient.Client) (uint16, error) {
	ret := _m.Called(_a0)

	var r0 uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint16, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint16); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleOfficialJobsFromJSONFile provides a mock function with given fields: _a0, collection, dataString
func (_m *Utils) HandleOfficialJobsFromJSONFile(_a0 *ethclient.Client, collection bindings.StructsCollection, dataString string) ([]bindings.StructsJob, []uint16) {
	ret := _m.Called(_a0, collection, dataString)

	var r0 []bindings.StructsJob
	var r1 []uint16
	if rf, ok := ret.Get(0).(func(*ethclient.Client, bindings.StructsCollection, string) ([]bindings.StructsJob, []uint16)); ok {
		return rf(_a0, collection, dataString)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client, bindings.StructsCollection, string) []bindings.StructsJob); ok {
		r0 = rf(_a0, collection, dataString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bindings.StructsJob)
		}
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client, bindings.StructsCollection, string) []uint16); ok {
		r1 = rf(_a0, collection, dataString)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]uint16)
		}
	}

	return r0, r1
}

// IsFlagPassed provides a mock function with given fields: name
func (_m *Utils) IsFlagPassed(name string) bool {
	ret := _m.Called(name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MultiplyFloatAndBigInt provides a mock function with given fields: bigIntVal, floatingVal
func (_m *Utils) MultiplyFloatAndBigInt(bigIntVal *big.Int, floatingVal float64) *big.Int {
	ret := _m.Called(bigIntVal, floatingVal)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(*big.Int, float64) *big.Int); ok {
		r0 = rf(bigIntVal, floatingVal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// PasswordPrompt provides a mock function with given fields:
func (_m *Utils) PasswordPrompt() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PrivateKeyPrompt provides a mock function with given fields:
func (_m *Utils) PrivateKeyPrompt() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Prng provides a mock function with given fields: max, prngHashes
func (_m *Utils) Prng(max uint32, prngHashes []byte) *big.Int {
	ret := _m.Called(max, prngHashes)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(uint32, []byte) *big.Int); ok {
		r0 = rf(max, prngHashes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// ReadJSONData provides a mock function with given fields: fileName
func (_m *Utils) ReadJSONData(fileName string) (map[string]*types.StructsJob, error) {
	ret := _m.Called(fileName)

	var r0 map[string]*types.StructsJob
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]*types.StructsJob, error)); ok {
		return rf(fileName)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]*types.StructsJob); ok {
		r0 = rf(fileName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*types.StructsJob)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecondsToReadableTime provides a mock function with given fields: input
func (_m *Utils) SecondsToReadableTime(input int) string {
	ret := _m.Called(input)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ToAssign provides a mock function with given fields: _a0
func (_m *Utils) ToAssign(_a0 *ethclient.Client) (uint16, error) {
	ret := _m.Called(_a0)

	var r0 uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client) (uint16, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ethclient.Client) uint16); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	if rf, ok := ret.Get(1).(func(*ethclient.Client) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WaitForBlockCompletion provides a mock function with given fields: _a0, hashToRead
func (_m *Utils) WaitForBlockCompletion(_a0 *ethclient.Client, hashToRead string) error {
	ret := _m.Called(_a0, hashToRead)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ethclient.Client, string) error); ok {
		r0 = rf(_a0, hashToRead)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WaitTillNextNSecs provides a mock function with given fields: waitTime
func (_m *Utils) WaitTillNextNSecs(waitTime int32) {
	_m.Called(waitTime)
}

// WriteDataToJSON provides a mock function with given fields: fileName, data
func (_m *Utils) WriteDataToJSON(fileName string, data map[string]*types.StructsJob) error {
	ret := _m.Called(fileName, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]*types.StructsJob) error); ok {
		r0 = rf(fileName, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUtils creates a new instance of Utils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUtils(t interface {
	mock.TestingT
	Cleanup(func())
}) *Utils {
	mock := &Utils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
