// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	abi "github.com/ethereum/go-ethereum/accounts/abi"

	mock "github.com/stretchr/testify/mock"
)

// AbiInterface is an autogenerated mock type for the AbiInterface type
type AbiInterface struct {
	mock.Mock
}

// Unpack provides a mock function with given fields: _a0, name, data
func (_m *AbiInterface) Unpack(_a0 abi.ABI, name string, data []byte) ([]interface{}, error) {
	ret := _m.Called(_a0, name, data)

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func(abi.ABI, string, []byte) []interface{}); ok {
		r0 = rf(_a0, name, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(abi.ABI, string, []byte) error); ok {
		r1 = rf(_a0, name, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAbiInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAbiInterface creates a new instance of AbiInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAbiInterface(t mockConstructorTestingTNewAbiInterface) *AbiInterface {
	mock := &AbiInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
