// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	big "math/big"
	bindings "razor/pkg/bindings"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"

	ethclient "github.com/ethereum/go-ethereum/ethclient"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// BlockManagerInterface is an autogenerated mock type for the BlockManagerInterface type
type BlockManagerInterface struct {
	mock.Mock
}

// ClaimBlockReward provides a mock function with given fields: _a0, _a1
func (_m *BlockManagerInterface) ClaimBlockReward(_a0 *ethclient.Client, _a1 *bind.TransactOpts) (*types.Transaction, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *types.Transaction
	if rf, ok := ret.Get(0).(func(*ethclient.Client, *bind.TransactOpts) *types.Transaction); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ethclient.Client, *bind.TransactOpts) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisputeBiggestStakeProposed provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *BlockManagerInterface) DisputeBiggestStakeProposed(_a0 *ethclient.Client, _a1 *bind.TransactOpts, _a2 uint32, _a3 uint8, _a4 uint32) (*types.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	var r0 *types.Transaction
	if rf, ok := ret.Get(0).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, uint32) *types.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, uint32) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisputeCollectionIdShouldBeAbsent provides a mock function with given fields: client, opts, epoch, blockIndex, id, positionOfCollectionInBlock
func (_m *BlockManagerInterface) DisputeCollectionIdShouldBeAbsent(client *ethclient.Client, opts *bind.TransactOpts, epoch uint32, blockIndex uint8, id uint16, positionOfCollectionInBlock *big.Int) (*types.Transaction, error) {
	ret := _m.Called(client, opts, epoch, blockIndex, id, positionOfCollectionInBlock)

	var r0 *types.Transaction
	if rf, ok := ret.Get(0).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, uint16, *big.Int) *types.Transaction); ok {
		r0 = rf(client, opts, epoch, blockIndex, id, positionOfCollectionInBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, uint16, *big.Int) error); ok {
		r1 = rf(client, opts, epoch, blockIndex, id, positionOfCollectionInBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisputeCollectionIdShouldBePresent provides a mock function with given fields: client, opts, epoch, blockIndex, id
func (_m *BlockManagerInterface) DisputeCollectionIdShouldBePresent(client *ethclient.Client, opts *bind.TransactOpts, epoch uint32, blockIndex uint8, id uint16) (*types.Transaction, error) {
	ret := _m.Called(client, opts, epoch, blockIndex, id)

	var r0 *types.Transaction
	if rf, ok := ret.Get(0).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, uint16) *types.Transaction); ok {
		r0 = rf(client, opts, epoch, blockIndex, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, uint16) error); ok {
		r1 = rf(client, opts, epoch, blockIndex, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisputeOnOrderOfIds provides a mock function with given fields: client, opts, epoch, blockIndex, index0, index1
func (_m *BlockManagerInterface) DisputeOnOrderOfIds(client *ethclient.Client, opts *bind.TransactOpts, epoch uint32, blockIndex uint8, index0 *big.Int, index1 *big.Int) (*types.Transaction, error) {
	ret := _m.Called(client, opts, epoch, blockIndex, index0, index1)

	var r0 *types.Transaction
	if rf, ok := ret.Get(0).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, *big.Int, *big.Int) *types.Transaction); ok {
		r0 = rf(client, opts, epoch, blockIndex, index0, index1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, *big.Int, *big.Int) error); ok {
		r1 = rf(client, opts, epoch, blockIndex, index0, index1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FinalizeDispute provides a mock function with given fields: client, opts, epoch, blockIndex, positionOfCollectionInBlock
func (_m *BlockManagerInterface) FinalizeDispute(client *ethclient.Client, opts *bind.TransactOpts, epoch uint32, blockIndex uint8, positionOfCollectionInBlock *big.Int) (*types.Transaction, error) {
	ret := _m.Called(client, opts, epoch, blockIndex, positionOfCollectionInBlock)

	var r0 *types.Transaction
	if rf, ok := ret.Get(0).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, *big.Int) *types.Transaction); ok {
		r0 = rf(client, opts, epoch, blockIndex, positionOfCollectionInBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ethclient.Client, *bind.TransactOpts, uint32, uint8, *big.Int) error); ok {
		r1 = rf(client, opts, epoch, blockIndex, positionOfCollectionInBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GiveSorted provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *BlockManagerInterface) GiveSorted(_a0 *bindings.BlockManager, _a1 *bind.TransactOpts, _a2 uint32, _a3 uint16, _a4 []uint32) (*types.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	var r0 *types.Transaction
	if rf, ok := ret.Get(0).(func(*bindings.BlockManager, *bind.TransactOpts, uint32, uint16, []uint32) *types.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*bindings.BlockManager, *bind.TransactOpts, uint32, uint16, []uint32) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Propose provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5, _a6
func (_m *BlockManagerInterface) Propose(_a0 *ethclient.Client, _a1 *bind.TransactOpts, _a2 uint32, _a3 []uint16, _a4 []uint32, _a5 *big.Int, _a6 uint32) (*types.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5, _a6)

	var r0 *types.Transaction
	if rf, ok := ret.Get(0).(func(*ethclient.Client, *bind.TransactOpts, uint32, []uint16, []uint32, *big.Int, uint32) *types.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ethclient.Client, *bind.TransactOpts, uint32, []uint16, []uint32, *big.Int, uint32) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
