// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TimeInterface is an autogenerated mock type for the TimeInterface type
type TimeInterface struct {
	mock.Mock
}

// Sleep provides a mock function with given fields: _a0
func (_m *TimeInterface) Sleep(_a0 time.Duration) {
	_m.Called(_a0)
}
