// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// TransactionInterfaceMockery is an autogenerated mock type for the TransactionInterfaceMockery type
type TransactionInterfaceMockery struct {
	mock.Mock
}

// Hash provides a mock function with given fields: _a0
func (_m *TransactionInterfaceMockery) Hash(_a0 *types.Transaction) common.Hash {
	ret := _m.Called(_a0)

	var r0 common.Hash
	if rf, ok := ret.Get(0).(func(*types.Transaction) common.Hash); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	return r0
}
